class KeyCode {
public:
	const static int KEY_0;
	const static int KEY_1;
	const static int KEY_2;
	const static int KEY_3;
	const static int KEY_4;
	const static int KEY_5;
	const static int KEY_6;
	const static int KEY_7;
	const static int KEY_8;
	const static int KEY_9;

	const static int KEY_A;
	const static int KEY_B;
	const static int KEY_C;
	const static int KEY_D;
	const static int KEY_E;
	const static int KEY_F;
	const static int KEY_G;
	const static int KEY_H;
	const static int KEY_I;
	const static int KEY_J;
	const static int KEY_K;
	const static int KEY_L;
	const static int KEY_M;
	const static int KEY_N;
	const static int KEY_O;
	const static int KEY_P;
	const static int KEY_Q;
	const static int KEY_R;
	const static int KEY_S;
	const static int KEY_T;
	const static int KEY_U;
	const static int KEY_V;
	const static int KEY_W;
	const static int KEY_X;
	const static int KEY_Y;
	const static int KEY_Z;

	const static int KEY_BACKSPACE;
	const static int KEY_TAB;
	const static int KEY_ENTER;
	const static int KEY_SHIFT;
	const static int KEY_CTRL;
	const static int KEY_PAUSE_BREAK;
	const static int KEY_CAPS_LOCK;
	const static int KEY_ESCAPE;
	const static int KEY_SPACE;
	const static int KEY_PAGE_UP;
	const static int KEY_PAGE_DOWN;
	const static int KEY_END;
	const static int KEY_HOME;
	const static int KEY_INSERT;
	const static int KEY_DELETE;
	const static int KEY_WINDOWS;
	const static int KEY_APPLICATION_KEY;

	const static int KEY_LEFT_ARROW;
	const static int KEY_UP_ARROW;
	const static int KEY_RIGHT_ARROW;
	const static int KEY_DOWN_ARROW;
};